(* File auto-generated by obus-gen-interface, DO NOT EDIT. *)
open OBus_member
module Org_freedesktop_DBus_Introspectable : sig
  val interface : OBus_name.interface
  val m_Introspect : (unit, string) Method.t
end
module Org_freedesktop_DBus_Peer : sig
  val interface : OBus_name.interface
  val m_GetMachineId : (unit, string) Method.t
  val m_Ping : (unit, unit) Method.t
end
module Org_freedesktop_DBus_Properties : sig
  val interface : OBus_name.interface
  val m_Get : (string * string, OBus_value.V.single) Method.t
  val m_GetAll : (string, (string * OBus_value.V.single) list) Method.t
  val m_Set : (string * string * OBus_value.V.single, unit) Method.t
  val s_PropertiesChanged : (string * (string * OBus_value.V.single) list * string list) Signal.t
end
module Org_mpris_MediaPlayer2 : sig
  val interface : OBus_name.interface
  val m_Quit : (unit, unit) Method.t
  val m_Raise : (unit, unit) Method.t
  val p_CanQuit : (bool, [ `readable ]) Property.t
  val p_CanRaise : (bool, [ `readable ]) Property.t
  val p_DesktopEntry : (string, [ `readable ]) Property.t
  val p_HasTrackList : (bool, [ `readable ]) Property.t
  val p_Identity : (string, [ `readable ]) Property.t
  val p_SupportedMimeTypes : (string list, [ `readable ]) Property.t
  val p_SupportedUriSchemes : (string list, [ `readable ]) Property.t
end
module Org_mpris_MediaPlayer2_Player : sig
  val interface : OBus_name.interface
  val m_Next : (unit, unit) Method.t
  val m_OpenUri : (string, unit) Method.t
  val m_Pause : (unit, unit) Method.t
  val m_Play : (unit, unit) Method.t
  val m_PlayPause : (unit, unit) Method.t
  val m_Previous : (unit, unit) Method.t
  val m_Seek : (int64, unit) Method.t
  val m_SetPosition : (OBus_path.t * int64, unit) Method.t
  val m_Stop : (unit, unit) Method.t
  val s_Seeked : int64 Signal.t
  val p_CanControl : (bool, [ `readable ]) Property.t
  val p_CanGoNext : (bool, [ `readable ]) Property.t
  val p_CanGoPrevious : (bool, [ `readable ]) Property.t
  val p_CanPause : (bool, [ `readable ]) Property.t
  val p_CanPlay : (bool, [ `readable ]) Property.t
  val p_CanSeek : (bool, [ `readable ]) Property.t
  val p_LoopStatus : (string, [ `readable | `writable ]) Property.t
  val p_MaximumRate : (float, [ `readable ]) Property.t
  val p_Metadata : ((string * OBus_value.V.single) list, [ `readable ]) Property.t
  val p_MinimumRate : (float, [ `readable ]) Property.t
  val p_PlaybackStatus : (string, [ `readable ]) Property.t
  val p_Position : (int64, [ `readable ]) Property.t
  val p_Rate : (float, [ `readable | `writable ]) Property.t
  val p_Shuffle : (bool, [ `readable | `writable ]) Property.t
  val p_Volume : (float, [ `readable | `writable ]) Property.t
end
